name: template_syntax
description: Template Syntax
version: 0.0.1
dependencies:
  angular2: 2.0.0-beta.0
  browser: ^0.10.0
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    entry_points: web/main.dart
