name: pipe_examples
description: Pipes Example
version: 0.0.1
dependencies:
  angular2: 2.0.0-beta.3
  browser: ^0.10.0
transformers:
- angular2:
    platform_directives: 'package:angular2/src/common/directives.dart#CORE_DIRECTIVES'
    platform_pipes: 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
