# #docregion
name: 'hierarchical_di'
description: Hierarchical dependency injection example
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
transformers:
- angular2:
    platform_directives: 'package:angular2/common.dart#COMMON_DIRECTIVES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
